pipeline {
    agent any

    environment {
        SONAR_HOST_URL = "http://sonarqube:9000"
        SONAR_TOKEN = credentials('sonar-token')
    }

    stages {

        stage('Checkout Code') {
            steps {
                checkout scm
            }
        }

        stage('SonarQube Analysis') {
            steps {
                sh '''
                docker run --rm \
                  --network cicd-net \
                  -e SONAR_HOST_URL=$SONAR_HOST_URL \
                  -e SONAR_LOGIN=$SONAR_TOKEN \
                  -v "$PWD:/usr/src" \
                  sonarsource/sonar-scanner-cli \
                  -Dsonar.projectKey=ci-cd-clean
                '''
            }
        }

        stage('Build Docker Image') {
            steps {
                sh 'docker build -t my-web-app ./app'
            }
        }

        stage('Deploy Container') {
            steps {
                sh '''
                docker rm -f webapp || true
                docker run -d -p 8081:80 --name webapp my-web-app
                '''
            }
        }
    }
}
