pipeline {
    agent any

    stages {
        stage('Clone Code') {
            steps {
                git 'https://github.com/Aniii-hub/basic-cicd.git'
            }
        }

        stage('Build Docker Image') {
            steps {
                sh 'docker build -t my-web-app ./app'
            }
        }

        stage('Deploy Container') {
            steps {
                sh '''
                docker stop webapp || true
                docker rm webapp || true
                docker run -d -p 8081:80 --name webapp my-web-app
                '''
            }
        }
    }
}
